<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\node\Entity\Node;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_views_pre_render()
 *
 * Add JS/CSS.
 *
 * @param ViewExecutable $view
 */
function asuaec_tuition_calendar_views_pre_render(ViewExecutable $view) {
    if ((isset($view) && ($view->storage->id() == 'important_dates')) ||
        (isset($view) && ($view->storage->id() == 'tuition_and_billing_calendar')) ||
        (isset($view) && ($view->storage->id() == 'financial_aid_calendar')) ||
        (isset($view) && ($view->storage->id() == 'tuition_and_billing_previous_semester_calendar'))
    ) {
        $view->element['#attached']['library'][] = 'asuaec_tuition_calendar/tuition-calendar-library';
    }
}

/**
 * Implements hook_theme
 *
 * Overwrite Views twig template
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return string[][]
 */
function asuaec_tuition_calendar_theme($existing, $type, $theme, $path){
    return [
        'views_view_table__financial_aid_calendar__attachment_1' => [
            'base hook' => 'views table'
        ],

    ];
}

///**
// * For testing
// * @param array $page
// */
//function asuaec_tuition_calendar_page_attachments_alter(array &$page) {
//    // Get the current path.
//    $current_path = \Drupal::service('path.current')->getPath();
//    if ($current_path == '/node/2576' || $current_path == '/node/2577') {
//        $page['#attached']['library'][] = 'asuaec_tuition_calendar/tuition-calendar-library2';
//        $page['#attached']['library'][] = 'core/drupal.dialog.ajax';
//    }
//}

/**
 * Implements hook_views_pre_view
 *
 * Set default value for when page loaded
 *
 * @param ViewExecutable $view
 * @param $display_id
 * @param array $args
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function asuaec_tuition_calendar_views_pre_view(ViewExecutable $view, $display_id, array &$args)
{
    // Tuition and Billing
    if (($view->id() == 'tuition_and_billing_calendar' && $display_id == "block_1") || ($view->id() == 'tuition_and_billing_calendar' && $display_id == "attachment_2")) {
        // Set default value for when page loaded
        $filters = $view->getDisplay()->getOption('filters');
        $filters["field_ps_value_value"]["value"] = getDefaultPsTermValue();
        $view->display_handler->overrideOption('filters', $filters);

    }

    // Term buttons - Set filter programaticaly. We want to show current semester and future semesters based on today's date. - Tuition and Billing
    if ($view->id() == 'tuition_and_billing_calendar' && $display_id == "block_3") {
        // Set default value for when page loaded
        $filters = $view->getDisplay()->getOption('filters');
        $filters["field_peoplesoft_value_numeric_value"]["operator"] = '>=';
//        ksm(getDefaultPsTermValue(), "getdefault");
        $filters["field_peoplesoft_value_numeric_value"]["value"]["value"] = getDefaultPsTermValue();
        $view->display_handler->overrideOption('filters', $filters);
    }

    // Financial aid
    // Set default value when page loaded.
    if (($view->id() == 'financial_aid_calendar' && $display_id == "block_1") || ($view->id() == 'financial_aid_calendar' && $display_id == "attachment_5")) {
        $filters = $view->getDisplay()->getOption('filters');
        unset($filters["field_academic_year_target_id"]["value"]);
        $filters["field_academic_year_target_id"]["value"][0] = getDefaultAcademicYearTid();
        $view->display_handler->overrideOption('filters', $filters);
    }

}

/**
 * Figure out what we should use for default value (ps_value) based on today's date (current time).
 *
 * @return mixed
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function getDefaultPsTermValue () {

    // Get academic_term taxonomy term data.
    $vid = 'academic_term';
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
    foreach ($terms as $term) {
        $term_obj = Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($term->tid);
//        ksm($term_obj->get('field_date_range2')->end_value, "end date");
        $term_data[] = [
            'tid' => $term->tid,
//    'tname' => $term->name,
            'ps_value' => $term_obj->get('field_ps_value')->value,
            'date_end' => $term_obj->get('field_date_range2')->end_value,
        ];
    }

    // Sorted by ps_value. Future ones first.
    usort($term_data, 'sortByPSValue');
    // Get timestamp of today's date (current time).
    $today_timestamp = time();
    //ksm($today_timestamp, "today_timestamp");
    //$today_timestamp = 1672531200; // For testing 1/1/2023

    // Finally, find out what we should use for default value.
    $i = 0;
    foreach($term_data as $data) {
        foreach($data as $key => $value) {
            if($key == "date_end") {
                if(getTimestamp($value) < $today_timestamp) {
                    // Stop there
                    break 2;
                }
            }
        }
        $i++;
    }
//    ksm($i, "i");
//    ksm($term_data[$i-1]['ps_value'], "ret val");
    return $term_data[$i-1]['ps_value'];
} // END OF function getDefaultPsTermValue ()

/**
 * Returns tid for the default year based on today's date (current time) - Financial aid
 *
 * @return mixed
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function getDefaultAcademicYearTid () {

    // Get academic_term taxonomy term data.
    $vid = 'academic_year';
    $years = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
    foreach ($years as $year) {
        $year_obj = Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($year->tid);
        $year_data[] = [
            'tid' => $year->tid,
            'name' => $year->name,
            'ps_value' => $year_obj->get('field_ps_value')->value,
            'date_end' => $year_obj->get('field_date_range2')->end_value, // <-- End date of the date range
        ];
    }
    // Sorted by date_range. Future ones first.
    usort($year_data, 'sortByPSValue');

    // Get timestamp of today's date (current time).
    $today_timestamp = time();
//    //$today_timestamp = 1672531200; // For testing 1/1/2023

    // Finally, find out what we should use for default value
    $i = 0;
    foreach($year_data as $data) {
        foreach($data as $key => $value) {
            if($key == "date_end") {
                if(getTimestamp($value) < $today_timestamp) {
                    // Stop there
                    break 2;
                }
            }
        }
        $i++;
    }
    return $year_data[$i-1]['tid'];
} // END OF function getDefaultAcademicYearTid ()

/**
 * Helping funciton - Get timestamp from '2022-5-17'.
 *
 * @param $date
 * @return int|void
 */
function getTimestamp($date) {
    $d = DateTime::createFromFormat('Y-m-d', $date);
    $timestamp = '';
    if ($d === false) {
        die("Incorrect date string");
    } else {
        $timestamp = $d->getTimestamp();
    }
    return $timestamp;
}

/**
 * Helping funciton - Used for sort by ps_value
 *
 * @param $a
 * @param $b
 * @return mixed
 */
function sortByPSValue($a, $b) {
//    return $a['ps_value'] - $b['ps_value']; // accending
    return $b['ps_value'] - $a['ps_value'];  // descending
}

//function sortByEndDate($a, $b) {
//
//    // creates DateTime objects
//    $datetime1 = date_create($a);
//    $datetime2 = date_create($b);
//
//    // calculates the difference between DateTime objects
//    $interval = date_diff($datetime1, $datetime2);
//
////    return $a['ps_value'] - $b['ps_value']; // accending
//    return $interval;  // descending
//}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Tuition and Billing previous semester calendar
 *   Change dropdown options (exposed filter) for semesters
 */
function asuaec_tuition_calendar_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    if ( $form_state->get('view')->id() == 'tuition_and_billing_previous_semester_calendar') {
        $options = $form['field_academic_term_target_id']['#options'];
        $form['field_academic_term_target_id']['#options'] = processAndSort($options);
    }
}

/**
 * Remove future semesters and sort.
 *
 * @param $options
 * @return array
 */
function processAndSort($options) {
    // Sort ascending first
    uasort($options, 'sortEntryTermAscending');

    $current_year_semester = getCurrentYearSemesterCombo(); // Get current "year semester" combo such as "2022 Spring"
    $options_processed = [];
    $temp_array = [];
    // Remove future years from array
    foreach ($options as $key => $value) {
        // if it is Any, remove it
        if($value == "- Any -") {
            $temp_array[$key] = "Please select a semester.";

        } else if($value == $current_year_semester) {
            // Stop there
            break;
        } else {
            $options_processed[$key] = $value;
        }
    }
    // Reverse array to decending
    uasort($options_processed, 'sortEntryTermDecending');
    // Add "Please select" at the top of the array
    $options_processed = $temp_array + $options_processed;
    return $options_processed;
}

/**
 * Used for sort decending by "year semester" combo such as "2022 Spring"
 *
 * @param $a
 * @param $b
 * @return mixed
 */
function sortEntryTermDecending($a, $b) {
    $a_exploded_array = explode(' ', $a);
    $b_exploded_array = explode(' ', $b);
    if($a_exploded_array[0] != $b_exploded_array[0]) { // $a_exploded_array[0] contains year such as 2022.
        return $b_exploded_array[0] - $a_exploded_array[0];
    } else {
        // Get term number: 1, 4, 7
        $a_term_num = getTermNumber($a_exploded_array[1]); // $a_exploded_array[1] contains semester such as "Spring"
        $b_term_num = getTermNumber($b_exploded_array[1]);
        return $b_term_num - $a_term_num;
    }
}

/**
 * Used for sort ascending by "year semester" combo such as "2022 Spring"
 *
 * @param $a
 * @param $b
 * @return mixed
 */
function sortEntryTermAscending($a, $b) {
    $a_exploded_array = explode(' ', $a);
    $b_exploded_array = explode(' ', $b);
    if($a_exploded_array[0] != $b_exploded_array[0]) { // $a_exploded_array[0] contains year such as 2022.
        return intval($a_exploded_array[0]) - intval($b_exploded_array[0]);

    } else {
        // Get term number: 1, 4, 7
        $a_term_num = getTermNumber($a_exploded_array[1]); // $a_exploded_array[1] contains semester such as "Spring"
        $b_term_num = getTermNumber($b_exploded_array[1]);
        return $a_term_num - $b_term_num;
    }
}

/**
 * Helping function
 * Return Entry term number: 1, 4 or 7
 *
 * @param $semester
 * @return int|void
 */
function getTermNumber($semester) {
    if($semester == "Spring") {
        return 1;
    } else if ($semester == "Summer") {
        return 4;
    } else if ($semester == "Fall") {
        return 7;
    }
}

/**
 * Helping function
 * Return current year and semester combo such as "2022 Spring"
 *
 * @return string
 */
function getCurrentYearSemesterCombo()
{
    $semester = '';
    // Today's date
    $current_year = date('Y'); // 2022
    $current_month = date('n'); // 1 through 12
    $current_date = date('j'); // 1 to 31

    if ($current_month >= 1 && $current_month <= 4) { // Jan - April
        $semester = "Spring";
    } else if ($current_month == 5) { // May
        if($current_date <= 15) {
            $semester = "Spring";
        } else {
            $semester = "Summer";
        }
    } else if (($current_month >= 6 && $current_month <= 7)) { // June - July
        $semester = "Summer";
    } else if ($current_month == 8) { // August
        if($current_date <= 6) {
            $semester = "Summer";
        } else {
            $semester = "Fall";
        }
    } else if (($current_month >= 9 && $current_month <= 12)) { // September - December
        $semester = "Fall";
    }
    return $current_year . " " . $semester;
}

/**
 * Implements hook_preprocess_TEMPLATE_NAME.
 *
 * Add unique_id to variables in order to use it in twig file.
 *
 * @param $variables
 */
function asuaec_tuition_calendar_preprocess_addtocal_links(&$variables) {
//    ksm("my test");

    foreach ($variables['items'] as &$item) {
        $id = $variables['button_attributes']->toArray()['id'];
        $variables['unique_id'] = $id;

    }
}