<?php

use Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException;
use Drupal\Component\Plugin\Exception\PluginNotFoundException;
use Drupal\Core\Access\AccessResultForbidden;
use Drupal\Core\Access\AccessResultNeutral;
use Drupal\Core\Entity\EntityStorageException;
use Drupal\user\UserInterface;
use Drupal\group\Entity\Group;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Deny access to student accounts.
 * Implements hook_simplesamlphp_auth_allow_login().
 *
 * @param array $attributes SAML attributes
 *
 * @return bool Whether the user is allowed to log in.
 */
function analytics_adfs_claims_handler_simplesamlphp_auth_allow_login(array $attributes): bool
{
  return !isset($attributes['eduPersonPrincipalName'][0]) || !str_contains(
      $attributes['eduPersonPrincipalName'][0],
      '@sundevils.asu.edu'
    );
}

/**
 * Ensure only group admins can change the AD groups.
 * Implements hook_entity_field_access().
 *
 * @param $operation
 * @param FieldDefinitionInterface $field_definition
 * @param AccountInterface $account
 * @param FieldItemListInterface|null $items
 *
 * @return AccessResult|AccessResultForbidden|AccessResultNeutral
 */
function adfs_claims_handler_entity_field_access(
  $operation,
  FieldDefinitionInterface $field_definition,
  AccountInterface $account,
  FieldItemListInterface $items = null
): AccessResultForbidden|AccessResultNeutral|AccessResult {
  if ($field_definition->getName() == 'adfs_claims_handler_pwr' || $field_definition->getName(
    ) == 'adfs_claims_handler_vwr') {
    return AccessResult::forbiddenIf(!$account->hasPermission('administer group'));
  }

  return AccessResult::neutral();
}

/**
 * Assign users to their proper Groups and roles upon login.
 * Implements hook_simplesamlphp_auth_user_attributes().
 *
 * @param UserInterface $account
 * @param $attributes
 *
 * @return UserInterface
 * @throws EntityStorageException
 * @throws InvalidPluginDefinitionException
 * @throws PluginNotFoundException
 */
function analytics_adfs_claims_handler_simplesamlphp_auth_user_attributes(
  UserInterface $account,
  $attributes
): UserInterface {
  $samlMail = $attributes['mail'] ?? '';
  $samlDisplayName = $attributes['Display-Name'] ?? '';
  $samlGroups = $attributes['group'] ?? [];

  // Ensure every user belongs to the 'AllAnalyticsUsers' group
  $samlGroups[] = 'AllAnalyticsUsers';

  // Update the proper user fields
  if ($samlMail) {
    $account->set('mail', $samlMail);
  }

  if ($samlDisplayName) {
    $account->set('field_name', $samlDisplayName);
  }

  // Assign the user to the proper groups
  $viewerGroups = analyticsSAMLAssignGroupMemberships($account, 'vwr', 'member', $samlGroups);
  $powerGroups = analyticsSAMLAssignGroupMemberships($account, 'pwr', 'power', $samlGroups);

  // Remove the user from the proper groups
  analyticsSAMLRemoveGroupMemberships($account, $viewerGroups, $powerGroups);

  return $account;
}

/**
 * Assign a user to their respective groups.
 *
 * @param UserInterface $account
 * @param string $permission
 * @param string $role
 * @param array $groups
 *
 * @return array|int
 * @throws EntityStorageException
 * @throws InvalidPluginDefinitionException
 * @throws PluginNotFoundException
 */
function analyticsSAMLAssignGroupMemberships(
  UserInterface $account,
  string $permission,
  string $role,
  array $groups
): array|int {
  $targetGroups = Drupal::entityTypeManager()
    ->getStorage('group')
    ->getQuery()
    ->condition("adfs_claims_handler_$permission", $groups, 'IN')
    ->accessCheck(false)
    ->execute();

  foreach ($targetGroups as $gid) {
    $group = Group::load($gid);
    $membership = $group->getMember($account);
    $userRole = "content_owner_group_ty-$role";
    $values = ['group_roles' => $userRole];

    if (!$membership) {
      $group->addMember($account, $values);
      $group->save();
    } elseif (!array_key_exists($userRole, $membership->getRoles())) {
      $group->removeMember($account);
      $group->save();
      $group->addMember($account, $values);
      $group->save();
    }
  }

  return $targetGroups;
}

/**
 * Remove the user from groups they do not belong to.
 *
 * @param UserInterface $account
 * @param array $viewerGroups
 * @param array $powerGroups
 *
 * @return void
 */
function analyticsSAMLRemoveGroupMemberships(UserInterface $account, array $viewerGroups, array $powerGroups): void
{
  $currentGroups = Drupal::service('group.membership_loader')->loadByUser($account);

  foreach ($currentGroups as $membership) {
    $group = $membership->getGroup();

    if (!in_array($group->id(), $viewerGroups) && !in_array($group->id(), $powerGroups)) {
      $group->removeMember($account);
      $group->save();
    }
  }
}
