<?php
use Drupal\Component\Utility\Html;
use Symfony\Component\Validator\Constraints\IsNull;
use Drupal\media\Entity\Media;
use Drupal\file\Entity\File;

/**
 * @file
 * Primary module hooks for Card View Format module.
 */


 /**
 * Prepares variables for card view format templates.
 *
 * Default template: views-view-card-view-format.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */


/**
 * Implements hook_theme().
 */
// function card_view_format_theme($existing, $type, $theme, $path) {
//     return array(
//       'card_view_format' => array(
//         'file' => 'card_view_format.theme.inc',
//       ),
//     );
// }



/**
 * Theme for card_view_format views.
 * This file is largely copied from template_preprocess_views_view_unformatted, with some additions.
 */

function template_preprocess_views_view_card_view_format(&$variables) {
  $view = $variables['view'];
  $rows = $variables['rows'];
  $style = $view->style_plugin;
  $options = $style->options;

  foreach ($rows as $id => $row) {
    $variables['rows'][$id] = [];
    $variables['rows'][$id]['content'] = $row;
    $entity = $variables['rows'][$id]['content']['#row']->_entity;
    if ($entity instanceof \Drupal\node\NodeInterface) {
      $myId = $entity->id();
      $node = \Drupal::entityTypeManager()->getStorage('node')->load($myId);
      // create easy variable to access link to node
      $read_more = $node->toUrl()->toString();
      // create variable to access image url
      if ($node->hasField('field_image_link')){
        $image_string = $node->field_image_link->value;
        if (!is_null($image_string)){
          $dom = Html::load($image_string);
          if (!is_null($dom)){
            foreach ($dom->getElementsByTagName('img') as $i => $img) {
              $img_url =  $img->getAttribute('src');
              $img_alt =  $img->getAttribute('alt');
            }
          }
        }
      }
      elseif ($node->hasField('field_media')) {
        $field_media = $node->get('field_media')->first();
        if ($field_media) {
          $field_media_image = Media::load($field_media->target_id)->get('field_media_image')->first();
          if ($field_media_image) {
            $file = File::load($field_media_image->target_id);
            if ($file) {
              $img_url = $file->createFileUrl();
            }
            $img_alt = $field_media_image->alt;
          }
        }
      }

      // *** Start: changes for ASU for you site ***
      //create variable to access image url, it's a media field boo
      if (!$node->hasField('field_image_link') && $node->hasField('field_resource_image')){
        $mid =  $node->get('field_resource_image')->getString();
        $media = Media::load($mid);
        $fid = $media->field_media_image->target_id;
        $img_alt =  $media->field_media_image->alt;
        $file = File::load($fid);
        $img_url = $file->createFileUrl();
      }
      // create link_href and link_text variables
      if ($node->hasField('field_resource_link')){
        if (!empty($node->field_resource_link->uri)) {
          $read_more = $node->field_resource_link->uri;
          $link_text = $node->field_resource_link->title;
        }
      }
      // *** End: changes for ASU for you site ***

      // create variable to access created date
      $createdTimeString = $node->getCreatedTime();
      $created = \Drupal::service('date.formatter')->format($createdTimeString, 'custom', 'F j, Y');
    }

    $variables['rows'][$id]['attributes'] = new Attribute();
    $variables['rows'][$id]['read_more'] = $read_more;
    $variables['rows'][$id]['img_url'] = $img_url;
    $variables['rows'][$id]['img_alt'] = $img_alt;
    $variables['rows'][$id]['created'] = $created;
    if ($row_class = $view->style_plugin->getRowClass($id)) {
      $variables['rows'][$id]['attributes']->addClass($row_class);
    }
  }

  $options = $variables['view']->style_plugin->options;
  $variables['options'] = $options;

}
