<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function asuaec_ecommerce_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    if($form_id == 'commerce_checkout_flow_multistep_default') {
        // Add JS/CSS
        $form['#attached']['library'][] = 'asuaec_ecommerce/ecommerce-library';
    }
}

/**
 * Implements hook_page_attachments_alter().
 */
function asuaec_ecommerce_page_attachments_alter(array &$page) {
    // Get the current path alias.
    $current_path = \Drupal::service('path.current')->getPath();
    $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
    if ($alias == '/cart') {
        // Include JS for cart
        $page['#attached']['library'][] = 'asuaec_ecommerce/ecommerce-library';
    }
    if ($alias == '/transcript' || $alias == '/thunderbird-transcript') {
        $page['#attached']['library'][] = 'asuaec_ecommerce/ecommerce-library-transcript';
    }
}