<?php
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render()
 *
 * Add JS/CSS.
 *
 * @param ViewExecutable $view
 */
function asuaec_faqs_views_pre_render(ViewExecutable $view) {
    if ((isset($view) && ($view->storage->id() == 'faqs2'))
    ) {
        $view->element['#attached']['library'][] = 'asuaec_faqs/asuaec-faqs-library';
    }
}

/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return string[][]
 *
 * Implements hook_theme().
 * Override Views template twigs from this module.
 *   /templates/views-view--faqs2--block-1.html.twig
 */
function asuaec_faqs_theme($existing, $type, $theme, $path){
    return [
        'views_view__faqs2__block_1' => [
            'render element' => 'elements',
            'base hook' => 'views'
        ],
        'views_view__faqs2__block_5' => [
            'render element' => 'elements',
            'base hook' => 'views'
        ],
        'views_view__faqs2__block_2' => [
            'render element' => 'elements',
            'base hook' => 'views'
        ],
    ];
}
