<?php

/**
 * Implements hook_preprocess_page().
 */
function trustees_utilities_preprocess_page(&$variables)
{
  $variables['#attached']['library'][] = 'trustees_utilities/global-styling';
}

/**
 * Implements hook_form_alter().
 */
function trustees_utilities_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if ($form_id === 'user_admin_permissions') {
    if (isset($form['actions']['submit'])) {
      $form['actions']['submit']['#disabled'] = TRUE;
    }
  }
}
