<?php

/**
 * @file
 * Preprocessors and helper functions to make theming easier.
 */

/**
 * Template node.
 */
function asu_tuition_preprocess_template(&$variable) {
  // \Drupal::logger('hello');
  // ksm($variable);
  /*if ($variable['node']->getType() === 'blog_posts') {
  $variable['my_title'] = $variable['node']->field_my_title->value;
  // \Drupal::logger('fcid')->notice(print_r($variable['my_title'], TRUE));


  }*/

}
