<?php
/**
 * ASU tuition estimator.
 *
 * Original Author: Marcus Anthony (marcus.anthony@asu.edu)
 * Created: 2011-05-20
 *
 * Drupal 9 version author: Archana Vannela (apuliroj@asu.edu)
 *
 * Refactored from asu_tuition which was a Drupal 7 module.
 */
use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

//$version = asu_tuition_get_module_version();
//define('ASU_TUITION_API_VERSION', $version['major'] . '.' . $version['minor']);
define('ASU_TUITION_PATH', 'tuition');
define('ASU_TUITION_PAGE_TITLE_DEFAULT', 'ASU Tuition Estimator');
define('ASU_TUITION_VALUE_NOT_SET', 'This value has not been set.');
define('ASU_TUITION_SEMESTER_CODE_FALL', 7);
define('ASU_TUITION_SEMESTER_CODE_SPRING', 1);
define('ASU_TUITION_CACHE_BIN', 'cache_asu_tuition');
define('ASU_TUITION_CACHE_LIFETIME_DEFAULT', 'CACHE_TEMPORARY');
define('ASU_TUITION_CACHE_LOG_DEFAULT', FALSE);
define('ASU_TUITION_WATCHDOG_TYPE', 'asu_tuition');
// Set money formats and locale for money_format() function.
define('ASU_TUITION_MONEY_FORMAT', '%.0n');
define('ASU_TUITION_MONEY_FORMAT_NO_DOLLAR_SIGN', '%!.0n');

/**
 * Get this modules version number breakdown. This was taken from drupal_parse_dependency().
 */
function asu_tuition_get_module_version() {
  module_load_include('module', 'system');

  // Core version is always optional: 7.x-2.x and 2.x is treated the same.
  $p_core = '(?:' . preg_quote('DRUPAL_CORE_COMPATIBILITY') . '-)?';
  $p_major = '(?P<major>\\d+)';
  // By setting the minor version to x, branches can be matched.
  $p_minor = '(?P<minor>(?:\\d+|x)(?:-[A-Za-z]+\\d+)?)';

  //$info = system_get_info('module', 'asu_tuition');
  $info = \Drupal::service('extension.list.module')->getExtensionInfo('asu_tuition');	
  $version = $info['version'];
  $matches = array();

  preg_match("/^\\s*{$p_core}{$p_major}\\.{$p_minor}/", $version, $matches);
  $matches['core'] = 'DRUPAL_CORE_COMPATIBILITY';
  return array_intersect_key($matches, array('core' => '', 'major' => '', 'minor' => ''));
	
}


/*function asu_tuition_theme($existing, $type, $theme, $path) {
  return array(
    'asu_tuition_search_page' => array(
      'file' => 'asu_tuition.pages.inc',
      'template' => 'asu-tuition-search-page',
    ),
    'asu_tuition_results_page' => array(
      'variables' => array(
        'op' => NULL,
        'values' => NULL,
        'results' => NULL
      ),
      'file' => 'asu_tuition.pages.inc',
      'template' => 'asu-tuition-results-page',
    ),
    'asu_tuition_cp_search_page' => array(
      'file' => 'asu_tuition.pages.inc',
      'template' => 'asu-tuition-search-page',
    ),
    'asu_tuition_cp_results_page' => array(
      'variables' => array(
        'op' => NULL,
        'values' => NULL,
        'results' => NULL
      ),
      'file' => 'asu_tuition.pages.inc',
      'template' => 'asu-tuition-results-page',
    ),
  );
}

function template_preprocess_asu_tuition(&$variables){
	
}*/

function get_data($table_name) {
		$table_name = "asu_tuition_acad_career";
	    $query = \Drupal::database()->select($table_name, 'tb');
		$query->fields('tb');
		$results = $query->execute()->fetchAll();
		//ksm($vars);
		//$results = get_object_vars ( $vars );
		//ksm($results);
		foreach($results as $object) {
		  foreach($object as $key=>$value) {
			 
			  $options[$key] = $key;
			  $ret[] = [
				  $key => $value
				  ];
			  //$ret['values'] = $values;
		  }
			
			
		}
		
 		//ksm($options);
		$header = $options;
		$ret['header'] = $options;
		//ksm($ret);
		return $ret;
  
    /*foreach ($res as $row) {
 
      $delete = Url::fromUserInput('/admin/structure/dn_students/students/delete/' . $row->id, array('attributes' => array('onclick' => "return confirm('Are you Sure')")));
      $edit = Url::fromUserInput('/admin/structure/dn_students/students/edit/' . $row->id);
      $edit_link = \Drupal::l('edit', $edit);
      $delete_link = \Drupal::l('delete', $delete);
 
      $mainLink = t('@linkApprove  @linkReject', array('@linkApprove' => $edit_link, '@linkReject' => $delete_link));
      
      $ret[] = [
        'id' => $row->id,
        'fname' => $row->fname,
		'sname' => $row->sname,
		'age' => $row->age,
		'marks' => $row->marks,
        'opt' => $mainLink,
      ];
    }
    return $ret;*/
}

//Implement hook_entity_type_build

/*function asu_tuition_entity_type_build(array &$entity_types){
	foreach (\Drupal::service('getSchema')->getSchema() as $table_name => $table) {
			$entity_info[$table_name] = array(
			  'label' => 'ASU Tuition - ' . str_replace('_', ' ', str_replace('asu_tuition_', '', $table_name)),
			  'entity class' => 'Entity',
			  'controller class' => 'EntityAPIController',
			  'base table' => $table_name,
			  'entity keys' => array(
				'id' => 'id',
			  ),
			  'module' => 'asu_tuition',
			);
  		}
	    ksm($entity_info); 
  		return $entity_info;
}*/



function asu_tuition_node_insert(NodeInterface $node) {
	//ksm($node->getType());
	$database = \Drupal::database();
	if($node->getType() == "asu_tuition_residency"){
		$nid = $node->id();
		//ksm($nid);
		$node_data =  Node::load($nid);
		//ksm($node_data);
		$description = $node_data->field_description->value;
		$residency = $node_data->field_residency->value;
		//ksm($residency);
		$display = $node_data->field_display->value;
		$weight = $node_data->field_weight->value;
		
		$check_data = $database->select('asu_tuition_residency','r')->fields('r',['id'])->condition('residency', $residency,'=')->execute()->fetchField();
		//ksm($check_data);
		if(empty($check_data)){
			$result = $database->insert('asu_tuition_residency')
			  ->fields([
				'residency' => $residency,
				'descr' => $description,
				'display' => $display,
				'weight' => $weight,  
			  ])
			  ->execute();
		}
		else{
			$messsage = "Could not insert node $nid into database base as the it was duplicate entry";
			//\Drupal::logger('asu_tuition_residency node message')->error($message);
			//\Drupal::logger('asu_tuition_residency node message')->notice(print_r($messsage, TRUE));
		}
	}
		
		//fee code
		//ksm($node->getType());
		if($node->getType() == "asu_tuition_fee_code_data"){
			$fnid = $node->id();
			//ksm($fnid);
			$f_node_data =  Node::load($fnid);
			//ksm($node_data);
			$acad_career = $f_node_data->field_acad_career->value;
			$fdescription = $f_node_data->field_code_description->value;
			$fresidency = $f_node_data->field_code_residency->value;
			$fee_code = $f_node_data->field_fee_code->value;	
			$fee_type = $f_node_data->field_fee_type->value;
			$institution = $f_node_data->field_institution->value;
			$field_notes = $f_node_data->field_notes->value;
			$campus = $f_node_data->field_campus->value;
			$acad_prog = $f_node_data->field_acad_prog->value;
			$base_term = $f_node_data->field_base_term->value;		
			//chck if node id already exists
			$check_fnid = $database->select('asu_tuition_fee_code','rfc')->fields('rfc',['id'])->condition('nodeid', $fnid,'=')->execute()->fetchField();
			//ksm($check_fnid);
			if(empty($check_fnid)){
				$result_fc = $database->insert('asu_tuition_fee_code')
					  ->fields([
						'institution' => $institution,
						'descr' => $fdescription,
						'fee_code' => $fee_code,
						'fee_type' => $fee_type,
						'campus' => $campus,
						'residency' => $fresidency,
						'acad_career' => $acad_career,
						'acad_prog' => $acad_prog,
						'base_term' => $base_term,
						'note' => $field_notes,
						'nodeid' => $fnid  
					  ])
					  ->execute();
			}
			else{
				$messsage_fnid = "Could not insert node $fnid into database base as the it was duplicate entry";
				//\Drupal::logger('asu_tuition_residency node message')->error($message);
				//\Drupal::logger('asu_tuition_fee_code node message')->notice(print_r($messsage_fnid, TRUE));
			}
		}
	
	
		//fee rate
		//ksm($node->getType());
		if($node->getType() == "asu_tuition_fee_rate_data"){
			$rnid = $node->id();
			//ksm($fnid);
			$r_node_data =  Node::load($rnid);
			//ksm($node_data);
			$r_institute = $r_node_data->field_rate_institution->value;
			$r_acad_year = $r_node_data->field_acad_year->value;
			$sterm = $r_node_data->field_sterm->value;
			$r_fee_code = $r_node_data->field_rate_fee_code->value;	
			$r_fee_type = $r_node_data->field_rate_fee_type->value;
			$enrolled_hrs = $r_node_data->field_enrolled_hrs->value;
			$fee_rate = $r_node_data->field_fee_rate->value;
			$check_rnid = $database->select('asu_tuition_fee_rate','fr')->fields('fr',['id'])->condition('nodeid', $rnid,'=')->execute()->fetchField();
			if(empty($check_rnid)){
			 $result_rate = $database->insert('asu_tuition_fee_rate')
				  ->fields([
					'institution' => $r_institute,
					'fee_code' => $r_fee_code,
					'fee_type' => $r_fee_type,
					'acad_year' => $r_acad_year,
					'strm' => $sterm,
					'enrlld_hrs' => $enrolled_hrs,  
					'fee_rate' => $fee_rate,
					'nodeid' => $rnid  
				  ])
				  ->execute();
			}
			else{
				$messsage_rnid = "Could not insert node $rnid into database base as the it was duplicate entry";
				//\Drupal::logger('asu_tuition_residency node message')->error($message);
				//\Drupal::logger('asu_tuition_fee_rate node message')->notice(print_r($messsag_rnid, TRUE));
			}
		}
			  
		
	
		
	//ksm($node);
}

//Code to redirect it to the default language if translation does not exist
function asu_tuition_preprocess_page(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if ($node instanceof \Drupal\node\NodeInterface) {
    $current_lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    if ($current_lang == 'es' && !$node->hasTranslation('es')) {
      $default_lang_url = Url::fromRoute('<current>', [], ['language' => \Drupal::languageManager()->getDefaultLanguage()])->toString();
      $response = new RedirectResponse($default_lang_url, 301);
      $response->send();
      exit;
    }
  }
}