<?php
use Drupal\Component\Utility\Html;
use Symfony\Component\Validator\Constraints\IsNull;
use Drupal\media\Entity\Media;
use Drupal\image\Entity\ImageStyle;
use Drupal\media_entity\MediaInterface;
use Drupal\node\Entity\Node;
use Drupal\file\Entity\File;

/**
 * @file
 * Primary module hooks for Card View Format module.
 */


 /**
 * Prepares variables for card view format templates.
 *
 * Default template: views-view-card-view-format.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */


/**
 * Implements hook_theme().
 */
// function card_view_format_asu_for_you_theme($existing, $type, $theme, $path) {
//     return array(
//       'card_view_format_asu_for_you' => array(
//         'file' => 'card_view_format_asu_for_you.theme.inc',
//       ),
//     );
// }



/**
 * Theme for card_view_format_asu_for_you views.
 * This file is largely copied from template_preprocess_views_view_unformatted, with some additions.
 */

function template_preprocess_views_view_card_view_format_asu_for_you(&$variables) {
  $view = $variables['view'];
  $rows = $variables['rows'];
  $style = $view->style_plugin;
  $options = $style->options;

  foreach ($rows as $id => $row) {
    $variables['rows'][$id] = [];
    $variables['rows'][$id]['content'] = $row;
    $entity = $variables['rows'][$id]['content']['#row']->_entity;
    if ($entity instanceof \Drupal\node\NodeInterface) {
      $myId = $entity->id();
      $node = \Drupal::entityTypeManager()->getStorage('node')->load($myId);
      //create variable to access image url, it's a media field boo
      if ($node->hasField('field_resource_image')){
        $mid =  $node->get('field_resource_image')->getString();
        $media = Media::load($mid);
        $fid = $media->field_media_image->target_id;
        $img_alt =  $media->field_media_image->alt;
        $file = File::load($fid);
        $img_url = $file->createFileUrl();
      }
      // create link_href and link_text variables
      if ($node->hasField('field_resource_link')){
        $link_href = $node->field_resource_link->uri;
        $link_text = $node->field_resource_link->title;
      }
      // create variable to access created date
      $createdTimeString = $node->getCreatedTime();
      $created = \Drupal::service('date.formatter')->format($createdTimeString, 'custom', 'F j, Y');
    }

    $variables['rows'][$id]['attributes'] = new Attribute();
    $variables['rows'][$id]['link_href'] = $link_href;
    $variables['rows'][$id]['link_text'] = $link_text;
    $variables['rows'][$id]['img_url'] = $img_url;
    $variables['rows'][$id]['img_alt'] = $img_alt;
    if ($row_class = $view->style_plugin->getRowClass($id)) {
      $variables['rows'][$id]['attributes']->addClass($row_class);
    }
  }

  $options = $variables['view']->style_plugin->options;
  $variables['options'] = $options;

}
