<?php

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_node().
 */
function chs_style_preprocess_node(&$variables) {
    $variables['#attached']['library'][] = 'chs_style/views_style';
}

function chs_style_form_content_moderation_entity_moderation_form_alter(&$form){
    $form['revision_log'] = [
        '#type' => 'textfield',
        '#title' => 'Log message',
        '#size' => 100,
        '#maxlength' => 5000,
      ];
}