<?php

use Drupal\asu_health_era\ComponentFactory;

function asu_health_era_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];

  $type = $paragraph->type->target_id;
  $component_builder = 'asu_health_era_process_component_' . $type;

  if (function_exists($component_builder)) {
    call_user_func_array($component_builder, [&$variables]);
  }
}
function asu_health_era_process_component_card(&$variables) {
  $paragraph = $variables['paragraph'];
  $settings = \Drupal::service('asu_react_core.helper_functions')->getCardContent($paragraph);
  $variables['content']['#attached']['drupalSettings']['asu'] = $settings;
}
function asu_health_era_process_component_card_with_icon(&$variables) {
  $paragraph = $variables['paragraph'];
  $settings = \Drupal::service('asu_react_core.helper_functions')->getCardContent($paragraph);
  $variables['content']['#attached']['drupalSettings']['asu'] = $settings;
}
function asu_health_era_preprocess_block(&$variables) {
  $plugin_id = $variables['base_plugin_id'] ?? '';

  if ($plugin_id != 'inline_block') {
    return;
  }

  $type = $variables['derivative_plugin_id'];
  $component = ComponentFactory::load($type);
  if ($component) {
    $component->buildSettings($variables);
  }
}

function asu_health_era_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'asu_health_era/healthlib';
}

function asu_health_era_theme() {
  return array(
    'block__inline_block__asu_health_era' => [
      'template' => 'block/block--inline-block--asu-health-era',
      'base hook' => 'block',
    ]
  );
}
