<?php

/**
 * Implements hook_theme().
 */
function asu_format_advising_theme($existing, $type, $theme, $path) {
  return [
    'form_asu_format_advising_multistep_form' => [
      'render element' => 'form',
      'template' => 'form--asu-format-advising-multistep-form'
    ],
    'element_summary' => [
      'variables' => ['element' => NULL, 'data' => ['bunny']],
      'path' => $path . '/templates',
      'template' => 'element-summary',
    ],
  ];
}

/**
 * Implements hook_field_widget_info_alter().
 */
function asu_format_advising_field_widget_info_alter(&$info) {
  if (isset($info['datetime_datelist'])) {
    $info['datetime_datelist']['class'] = 'Drupal\asu_format_advising\Plugin\Field\FieldWidget\CustomDateWidget';
  }
}
