<?php

use Drupal\Core\Database\Database;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function asuaec_viewbook_webformhandler_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    if (isset($form['#webform_id']) && $form['#webform_id'] == 'viewbook') {
        // Add JS/CSS
        //$form['#attached']['library'][] = 'asuaec_viewbook_webformhandler/viewbook-webformhandler-library';
    }
}

/**
 * Implements hook_mail().
 */
function asuaec_viewbook_webformhandler_mail($key, &$message, $params) {
    $options = array(
        'langcode' => $message['langcode'],
    );
    switch ($key) {
        case 'rfi_conf_email':
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = t('@subject', ['@subject' => $params['subject']], $options);
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed'; // Needed this to display images.
            $message['body'][] = $params['message'];
            break;
    }
}
