<html>
<head>
<style type="text/css" media="all">
@import url("/profiles/openasu/themes/innovation/css/innovation-main.css?nv5de8");
@import url("/profiles/openasu/themes/innovation/css/buttons.css?nv5de8");
@import url("/profiles/openasu/themes/innovation/css/forms.css?nv5de8");
@import url("/profiles/openasu/themes/innovation/css/nav.css?nv5de8");
@import url("/profiles/openasu/themes/innovation/fonts/roboto/css/roboto.css?nv5de8");
@import url("/sites/all/themes/innovation_asu_news/css/main.css?nv5de8");
</style>

<!-- The following code was generated by Exacttarget.com. Please do not edit. //--> 
<SCRIPT language="Javascript"> 
<!-- 
// isEmail (STRING s [, BOOLEAN emptyOK])
// whitespace characters
var whitespace = " \t\n\r";

// 
// Email address must be of form a@b.c ... in other words:
// * there must be at least one character before the @
// * there must be at least one character before and after the .
// * the characters @ and . are both required
function isValidEmail(s)
{   
	if (isEmpty(s)) return false;
   
	// is s whitespace?
	if (isWhitespace(s)) return false;
	    
	// there must be >= 1 character before @, so we
	// start looking at character position 1 
	// (i.e. second character)
	var i = 1;
	var sLength = s.length;

	// look for @
	while ((i < sLength) && (s.charAt(i) != "@"))
	{ i++
	}

	if ((i >= sLength) || (s.charAt(i) != "@")) return false;
	else i += 2;

	// look for .
	while ((i < sLength) && (s.charAt(i) != "."))
	{ i++
	}

	// there must be at least one character after the .
	if ((i >= sLength - 1) || (s.charAt(i) != ".")) return false;
	else return true;
}

// Check whether string s is empty.
function isEmpty(s)
{   
	return ((s == null) || (s.length == 0))
}

// Returns true if string s is empty or 
// whitespace characters only.
function isWhitespace(s)
{   
	var i;

    // Is s empty?
    if (isEmpty(s)) return true;

    // Search through string's characters one by one
    // until we find a non-whitespace character.
    // When we do, return false; if we don't, return true.
    for (i = 0; i < s.length; i++)
    {   
		// Check that current character isn't whitespace.
		var c = s.charAt(i);

		if (whitespace.indexOf(c) == -1) return false;
    }
    // All characters are whitespace.
    return true;
}

function checkForm() { 
	z=0;
	celements=document.getElementsByName('lid');
		for (c=0;c<celements.length;c++){
		if (celements[c].checked){
			z=z+1;
			}
		}
	if (z<1){
	alert("Please select at least one list.");
		return false;
	}
	if (!isValidEmail(document.subscribeForm.elements['Email Address'].value)) {
	document.subscribeForm.elements['Email Address'].style.backgroundColor='yellow';
		alert("Please enter a valid Email Address. (name@host.com)");
		document.subscribeForm.elements['Email Address'].focus();
		return false;
	}
}
//--> 
</SCRIPT> 

</head>

<body>
<form action="http://cl.s7.exct.net/subscribe.aspx" name="subscribeForm" method="post" onSubmit="return checkForm();">
<input type="hidden" name="thx" value="/sites/all/themes/innovation_asu_news/subscription_center/thankyou.php">
<input type="hidden" name="err" value="/sites/all/themes/innovation_asu_news/subscription_center/error.php">
<input type="hidden" name="usub" value="/sites/all/themes/innovation_asu_news/subscription_center/unsubscribe.php">
<input type="hidden" name="MID" value="7201488">
<input type="hidden" name="Media Relations" value="TRUE" />

<table cellpadding="0" cellspacing="0" border="0">
<tr>
<td>First Name:</td>
<td><input type="text" name="First Name"></td>
</tr>
<tr>
<td>Last Name:</td>
<td><input type="text" name="Last Name"></td>
</tr>
<tr>
<td>Email:</td>
<td><input type="text" name="Email Address"></td>
</tr>
<tr>
<td>
Format:
</td>
<td>
<input type="radio" name="Email Type" value="HTML" checked>
HTML &nbsp;&nbsp;<input type="radio" name="Email Type" value="TEXT">
Text
</td>
</tr>
<tr>
<td>Edition:
</td>
<td><input type="checkbox" name="lid" value="2844"> ASU Now Daily &nbsp;&nbsp;
<input type="checkbox" name="lid" value="2846">
ASU Insight (Employee news)</td>
</tr>
<td>
</td>
<td><input type="radio" name="SubAction" value="sub_add_update" checked>
Subscribe &nbsp;&nbsp;<input type="radio" name="SubAction" value="unsub">
Unsubscribe
</td>
<tr>
<td><input type="submit" value="Submit"></td>
<td align="right">
</td>
</tr> </table> </form>
</body>
</html>