<?php

/**
 * @file
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\crop\Entity\Crop;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Form\FormStateInterface;

function asumex_custom_theme($existing, $type, $theme, $path) {

  return [
    // Ghost block to apply styles and scripts
    'asumex_block' => [
      'variables' => [],
    ],

    // Mailchimp Subscribe Form
    'asumex_mailchimp' => [
      'variables' => [],
    ],

  ];
}

function asumex_custom_css_alter(&$css, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {

  $path = \Drupal::service('extension.list.module')->getPath('asumex_custom') . '/css/custom.css';
  if (isset($css[$path])) {
    // Use anything greater than 100 to have it load after the theme as CSS_AGGREGATE_THEME is set to 100.
    $css[$path]['group'] = 300;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 */
function asumex_custom_preprocess_html(&$variables) {
  $path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);
  if (isset($path_args[1]) && isset($path_args[2]) && ($path_args[1] == 'node') && (is_numeric($path_args[2]))) {
    $variables['attributes']['class'][] = 'page-node-' . $path_args[2];
  }

  $variables['base_path'] = base_path();
}


/**
 * @} End.
 */
