#!/bin/bash
## Description: Automatically fix PHP CodeSniffer errors
## Usage: phpcbf
## Example: ddev phpcbf [options] [file|directory...]

./vendor/bin/phpcbf -n -d memory_limit=512M --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml --ignore=node_modules,bower_components,vendor --colors "$@"
